Repository chemelia/city-planning-game, pull requests merged in 2022-03, with the labels that each got.

#1 Add PR template for prposing changes
  .github/pull_request_template.md
Labels: enhancement

#6 add player manager template
  city planning game/Assets/Scripts/PlayerManager.cs
Labels: enhancement

#7 add basic scene management
  city planning game/Assets/Scripts/Level.cs
  city planning game/Assets/Scripts/SceneController.cs
Labels: enhancement

#8 UI
  city planning game/Assets/Prefabs/BuildingButton.prefab
  city planning game/Assets/Prefabs/BuildingButton.prefab.meta
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/GameManager.cs
  city planning game/Assets/Scripts/MouseInput.cs
Labels: enhancement

#11 very basic building placement with no collision detection
  city planning game/Assets/Prefabs/Buildings.meta
  city planning game/Assets/Prefabs/Buildings/HouseSmall.prefab
  city planning game/Assets/Prefabs/Buildings/HouseSmall.prefab.meta
  city planning game/Assets/Prefabs/DialogueText.prefab.meta
  city planning game/Assets/Resources.meta
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/Building.cs
  city planning game/Assets/Scripts/BuildingAffinity.cs
  city planning game/Assets/Scripts/BuildingAffinity.cs.meta
  city planning game/Assets/Scripts/BuildingsData.cs
  city planning game/Assets/Scripts/Character.cs.meta
  city planning game/Assets/Scripts/Dialogue.cs.meta
  city planning game/Assets/Scripts/DialogueManager.cs.meta
  city planning game/Assets/Scripts/GameManager.cs
  city planning game/Assets/Scripts/Level.cs.meta
  city planning game/Assets/Scripts/PlacementController.cs
  city planning game/Assets/Scripts/PlacementController.cs.meta
  city planning game/Assets/Scripts/PlayerManager.cs.meta
  city planning game/Assets/Scripts/SceneController.cs.meta
  city planning game/Assets/Scripts/Util.cs.meta
  city planning game/Assets/TextMesh Pro.meta
  city planning game/ProjectSettings/DynamicsManager.asset
  city planning game/ProjectSettings/Physics2DSettings.asset
  city planning game/ProjectSettings/ProjectSettings.asset
  city planning game/ProjectSettings/SceneTemplateSettings.json
  city planning game/ProjectSettings/TagManager.asset
  city planning game/ProjectSettings/TimelineSettings.asset
Labels: enhancement

#13 import building meshes
  city planning game/Assets/Models.meta
  city planning game/Assets/Models/building_cityhall_v1.obj
  city planning game/Assets/Models/building_cityhall_v1.obj.meta
  city planning game/Assets/Models/building_default.preset
  city planning game/Assets/Models/building_default.preset.meta
  city planning game/Assets/Models/building_factory_v1.obj
  city planning game/Assets/Models/building_factory_v1.obj.meta
  city planning game/Assets/Models/building_luxuryapts_v1.obj
  city planning game/Assets/Models/building_luxuryapts_v1.obj.meta
  city planning game/Assets/Models/building_office_v1.obj
  city planning game/Assets/Models/building_office_v1.obj.meta
  city planning game/Assets/Models/building_publichousing_v1.obj
  city planning game/Assets/Models/building_publichousing_v1.obj.meta
  city planning game/Assets/Models/building_smallhouse_v1.obj
  city planning game/Assets/Models/building_smallhouse_v1.obj.meta
  city planning game/Assets/Models/building_suburbhouse_v1.obj
  city planning game/Assets/Models/building_suburbhouse_v1.obj.meta
  city planning game/Assets/Models/building_townhouse_v1.obj
  city planning game/Assets/Models/building_townhouse_v1.obj.meta
  city planning game/Assets/Models/terrain_v1.obj
  city planning game/Assets/Models/terrain_v1.obj.meta
  city planning game/Assets/Prefabs/Buildings/HouseSmall.prefab
  city planning game/Assets/Scenes/SampleScene.unity
Labels: enhancement

#19 building prefab bugfixes
  city planning game/Assets/Prefabs/Buildings/HouseSmall.prefab
  city planning game/Assets/Scripts/Building.cs
  city planning game/Assets/Scripts/PlacementController.cs
Labels: bug

#15 unbind zoom from mouse scroll
  city planning game/Assets/Scripts/CameraControl.cs
  city planning game/ProjectSettings/InputManager.asset
Labels: bug, invalid

#20 Social Media Feed Scaling Fix
  city planning game/Assets/Prefabs/DialogueText.prefab
  city planning game/Assets/Scenes/SampleScene.unity
Labels: bug

#23 General UI work + made a ToString() function in Building.cs
  city planning game/Assets/Prefabs/Buildings/House Small.prefab
  city planning game/Assets/Prefabs/Buildings/House Small.prefab.meta
  city planning game/Assets/Prefabs/Buildings/House Suburb.prefab
  city planning game/Assets/Prefabs/Buildings/House Suburb.prefab.meta
  city planning game/Assets/Prefabs/DialogueText.prefab
  city planning game/Assets/Prefabs/ProgressBar.prefab
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/Building.cs
  city planning game/Assets/Scripts/BuildingPanelUI.cs
  city planning game/ProjectSettings/TagManager.asset
Labels: enhancement

#24 fix dialogue file names
  city planning game/Assets/Prefabs/DialogueText.prefab
  city planning game/Assets/Scripts/DialogueManager.cs
Labels: bug

#26 Building Affinities
  city planning game/Assets/Prefabs/Buildings/AptLow.prefab
  city planning game/Assets/Prefabs/Buildings/AptLuxury.prefab
  city planning game/Assets/Prefabs/Buildings/Factory.prefab
  city planning game/Assets/Prefabs/Buildings/House Small.prefab
  city planning game/Assets/Prefabs/Buildings/House Suburb.prefab
  city planning game/Assets/Prefabs/Buildings/OfficeTower.prefab
  city planning game/Assets/Prefabs/Buildings/School.prefab
  city planning game/Assets/Prefabs/Buildings/TownHall.prefab
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/Building.cs
  city planning game/Assets/Scripts/GameManager.cs
  city planning game/Assets/Scripts/Level.cs
  city planning game/Assets/Scripts/PlacementController.cs
  city planning game/Assets/Scripts/PlayerManager.cs
  city planning game/Assets/Scripts/UI/UI_ProgressBar.cs
Labels: enhancement
