Repository chemelia/city-planning-game, pull requests merged in 2022-04, with the labels that each got.

#29 add basic building cost
  city planning game/Assets/Prefabs/Buildings/AptLow.prefab
  city planning game/Assets/Prefabs/Buildings/AptLuxury.prefab
  city planning game/Assets/Prefabs/Buildings/Factory.prefab
  city planning game/Assets/Prefabs/Buildings/House Small.prefab
  city planning game/Assets/Prefabs/Buildings/House Suburb.prefab
  city planning game/Assets/Prefabs/Buildings/OfficeTower.prefab
  city planning game/Assets/Prefabs/Buildings/School.prefab
  city planning game/Assets/Prefabs/Buildings/TownHall.prefab
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/Building.cs
  city planning game/Assets/Scripts/GameManager.cs
  city planning game/Assets/Scripts/PlacementController.cs
  city planning game/Assets/Scripts/PlayerManager.cs
Labels: enhancement

#30 Queue Inventory System
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/BuildingPanelUI.cs
  city planning game/Assets/Scripts/GameManager.cs
  city planning game/Assets/Scripts/PlacementController.cs
Labels: enhancement

#32 Building Indicators
  city planning game/Assets/Prefabs/Buildings/AptLow.prefab
  city planning game/Assets/Prefabs/Buildings/AptLuxury.prefab
  city planning game/Assets/Prefabs/Buildings/Factory.prefab
  city planning game/Assets/Prefabs/Buildings/House Small.prefab
  city planning game/Assets/Prefabs/Buildings/House Suburb.prefab
  city planning game/Assets/Prefabs/Buildings/OfficeTower.prefab
  city planning game/Assets/Prefabs/Buildings/School.prefab
  city planning game/Assets/Prefabs/Buildings/TownHall.prefab
  city planning game/Assets/Scripts/Building.cs
  city planning game/Assets/Scripts/PlayerManager.cs
Labels: enhancement

#33 Levels
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/Building.cs
  city planning game/Assets/Scripts/BuildingPanelUI.cs
  city planning game/Assets/Scripts/Character.cs
  city planning game/Assets/Scripts/DialogueManager.cs
  city planning game/Assets/Scripts/GameManager.cs
  city planning game/Assets/Scripts/Level.cs
  city planning game/Assets/Scripts/PlacementController.cs
  city planning game/Assets/Scripts/Quest.cs
  city planning game/Assets/Scripts/SceneController.cs
  city planning game/Assets/Scripts/UI/UI_ProgressBar.cs
Labels: enhancement

#35 camera panning keyboard controls!!
  city planning game/Assets/Models/building_factory_v1.obj.meta
  city planning game/Assets/Models/building_luxuryapts_v1.obj.meta
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/CameraControl.cs
  city planning game/Assets/Scripts/PlacementController.cs
  city planning game/ProjectSettings/InputManager.asset
Labels: enhancement

#36 Fix quests
  city planning game/Assets/Prefabs/Buildings/AptLow.prefab
  city planning game/Assets/Prefabs/Buildings/AptLuxury.prefab
  city planning game/Assets/Prefabs/Buildings/Factory.prefab
  city planning game/Assets/Prefabs/Buildings/House Small.prefab
  city planning game/Assets/Prefabs/Buildings/House Suburb.prefab
  city planning game/Assets/Prefabs/Buildings/OfficeTower.prefab
  city planning game/Assets/Prefabs/Buildings/School.prefab
  city planning game/Assets/Prefabs/Buildings/TownHall.prefab
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/BuildingPanelUI.cs
  city planning game/Assets/Scripts/GameManager.cs
  city planning game/Assets/Scripts/Quest.cs
  city planning game/Assets/Scripts/Quest.cs.meta
Labels: bug, enhancement

#40 Main Menu, sans proper options
  city planning game/Assets/Scenes/Main Menu.unity
  city planning game/Assets/Scenes/Main Menu.unity.meta
  city planning game/Assets/Scripts/MainMenu.cs
  city planning game/Assets/Scripts/MainMenu.cs.meta
  city planning game/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  city planning game/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#39 Remove building indicators when deselcting a building
  city planning game/Assets/Scripts/Building.cs
  city planning game/Assets/Scripts/PlacementController.cs
Labels: bug

#48 Main Menu Options
  city planning game/Assets/FMOD Builds/Desktop/Master.bank
  city planning game/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  city planning game/Assets/Scenes/Main Menu.unity
  city planning game/Assets/Scripts/UI/AudioMixerBar.cs
  city planning game/Assets/Scripts/UI/AudioMixerBar.cs.meta
Labels: enhancement

#47 Add profile icons for social feed
  city planning game/Assets/Resources/Portraits/sports.png
  city planning game/Assets/Resources/Portraits/sports.png.meta
  city planning game/Assets/Resources/Portraits/weather.png
  city planning game/Assets/Resources/Portraits/weather.png.meta
  city planning game/Assets/Resources/Profiles.meta
  city planning game/Assets/Resources/Profiles/betsy.png
  city planning game/Assets/Resources/Profiles/betsy.png.meta
  city planning game/Assets/Resources/Profiles/david.png
  city planning game/Assets/Resources/Profiles/david.png.meta
  city planning game/Assets/Resources/Profiles/gulliver.png
  city planning game/Assets/Resources/Profiles/gulliver.png.meta
  city planning game/Assets/Resources/Profiles/marcia.png
  city planning game/Assets/Resources/Profiles/marcia.png.meta
  city planning game/Assets/Resources/Profiles/mark.png
  city planning game/Assets/Resources/Profiles/mark.png.meta
  city planning game/Assets/Resources/Profiles/mayor.png
  city planning game/Assets/Resources/Profiles/mayor.png.meta
  city planning game/Assets/Resources/Profiles/sports.png
  city planning game/Assets/Resources/Profiles/sports.png.meta
  city planning game/Assets/Resources/Profiles/tmp.png
  city planning game/Assets/Resources/Profiles/tmp.png.meta
  city planning game/Assets/Resources/Profiles/weather.png
  city planning game/Assets/Resources/Profiles/weather.png.meta
  city planning game/Assets/Resources/Sports-Channel.txt
  city planning game/Assets/Resources/Weather-Channel.txt
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/Character.cs
  city planning game/Assets/Scripts/UI/DialogueManager.cs
Labels: enhancement

#50 Update building meshes and remove cost for choosing buildings
  city planning game/Assets/Prefabs/Buildings/FastFood.prefab
  city planning game/Assets/Prefabs/Buildings/Hospital.prefab
  city planning game/Assets/Prefabs/Buildings/Mall.prefab
  city planning game/Assets/Prefabs/Buildings/Mansion.prefab
  city planning game/Assets/Prefabs/Buildings/OilRig.prefab
  city planning game/Assets/Prefabs/Buildings/Warehouse.prefab
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/GameManager.cs
Labels: enhancement

#52 Add basic storyline for betsy
  city planning game/Assets/Resources/Betsy.txt
  city planning game/Assets/Resources/Gulliver.txt
  city planning game/Assets/Scenes/SampleScene.unity
  city planning game/Assets/Scripts/Character.cs
  city planning game/Assets/Scripts/GameManager.cs
  city planning game/Assets/Scripts/Quest.cs
  city planning game/Assets/Scripts/UI/DialogueManager.cs
  city planning game/Assets/Scripts/UI/DialoguePopup.cs
Labels: enhancement
